name: IAM Roles Deployment Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-iam:
    name: Deploy IAM Roles on Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          echo " Logged into Azure successfully"

      - name: Make Script Executable
        run: chmod +x scripts/iam_setup.sh

      - name: Run IAM Setup Script
        run: bash scripts/iam_setup.sh

      - name: Confirm Deployment
        run: |
          echo "Pipeline complete!"
          az group show \
            --name IAM-Project-RG \
            --query "{Name:name, Location:location, State:properties.provisioningState}" \
            --output table